{% set version = "0.9.1" %}

package:
  name: wake-t
  version: {{ version }}

source:
  url: https://github.com/AngelFP/Wake-T/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bdf4fee6a8939b79b63666ac29a94015dcf4ca632bc502ecd68fce2072059f5b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aptools
    - lasy >=0.7
    - numba
    - numpy
    - openpmd-api
    - python >={{ python_min }}
    - scipy
    - tqdm

test:
  requires:
    - matplotlib-base
    - openpmd-viewer
    - python {{ python_min }}
    - pytest
  source_files:
    - examples/
    - tests/
  imports:
    - wake_t

about:
  home: https://wake-t.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A fast tracking code for plasma accelerators

  description: |
    Wake-T (Wakefield particle Tracker) is a tracking code for laser- and
    beam-driven plasma wakefield accelerators which aims at providing a fast
    alternative to Particle-in-Cell (PIC) simulations. Instead of relying on
    the computationally-expensive PIC algorithm for simulating the plasma
    wakefields and the beam evolution, Wake-T uses a Runge-Kutta solver to
    track the evolution of the beam electrons in the wakefields, which, at
    the same time, are computed from reduced models.
  dev_url: https://github.com/AngelFP/Wake-T

extra:
  recipe-maintainers:
    - AngelFP
    - ax3l
    - MaxThevenet
